import sys
input = sys.stdin.readline

"""
A 10x10 target is made out of five "rings" as shown. Each ring has a different point value: the outermost ring — 1 point, the next ring — 2 points, ..., the center ring — 5 points.
Vlad fired several arrows at the target. Help him determine how many points he got.

Input
The input consists of multiple test cases. The first line of the input contains a single integer t (1≤t≤1000) — the number of test cases.

Each test case consists of 10 lines, each containing 10 characters. Each character in the grid is either X (representing an arrow) or . (representing no arrow).

Output
For each test case, output a single integer — the total number of points of the arrows.

Example

Input
4
X.........
..........
.......X..
.....X....
......X...
..........
.........X
..X.......
..........
.........X
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
....X.....
..........
..........
..........
..........
..........
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX

Output
17
0
5
220
"""

t = int(input())

for _ in range(t):
    ans = 0

    for i in range(10):
        s = input().strip()

        for j in range(10):
            if s[j] == 'X':
                ans += min(i + 1, j + 1, 10 - i, 10 - j)

    print(ans)